package com.example.foldback.encrogram.ui

import android.app.Application
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.example.foldback.encrogram.DecryptOutcome
import com.example.foldback.encrogram.Encrogram
import com.example.foldback.encrogram.crypto.Encryptor
import com.example.foldback.encrogram.format.InnerPayload
import com.example.foldback.encrogram.session.UnlockedPhrase
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch

/**
 * Zustand der Encrogram-Hauptseite. Klartext, erzeugte Sätze und Ergebnisse liegen nur hier im RAM
 * (nie in rememberSaveable) und werden bei jeder Sperre gelöscht.
 */
class EncrogramViewModel(application: Application) : AndroidViewModel(application) {

    private val encrogram = Encrogram.get(application)

    val phrases: StateFlow<List<UnlockedPhrase>> = encrogram.session.phrases

    var selected by mutableStateOf<UnlockedPhrase?>(null)
        private set
    var message by mutableStateOf("")
    var busy by mutableStateOf(false)
        private set
    var error by mutableStateOf<String?>(null)
        private set
    var result by mutableStateOf<DecryptOutcome?>(null)
        private set
    var generated by mutableStateOf<List<String>?>(null)
        private set
    var generatedBits by mutableStateOf(0.0)
        private set
    var addingPhrase by mutableStateOf(false)
    var senderName by mutableStateOf(encrogram.settings.senderName)
        private set

    /** Erhöht sich, wenn Encrogram verlassen wird; setzt halb getippte Sätze zurück. */
    var resetCount by mutableIntStateOf(0)
        private set

    val reminderDue: Boolean get() = encrogram.rotationReminder.isDue

    /** Wie viele Byte noch in die Nachricht passen; negativ = zu lang. */
    val remainingBytes: Int get() = Encryptor.remainingBytes(message, senderName)

    init {
        viewModelScope.launch {
            phrases.collect { list ->
                if (list.isEmpty()) clearSensitive()
                if (selected !in list) selected = list.lastOrNull()
            }
        }
    }

    fun touch() = encrogram.touch()

    fun select(phrase: UnlockedPhrase) {
        selected = phrase
    }

    fun unlock(input: String) = launchBusy {
        val phrase = encrogram.unlock(input)
        if (phrase == null) {
            error = "Gesperrt, bevor der Satz geprüft war. Bitte erneut eingeben."
        } else {
            selected = phrase
            addingPhrase = false
        }
    }

    fun encrypt(onReady: (String) -> Unit) {
        val phrase = selected ?: return
        launchBusy {
            val ciphertext = encrogram.encrypt(message, phrase)
            if (ciphertext == null) {
                error = "Der Satz wurde gesperrt. Bitte erneut entsperren."
            } else {
                message = ""
                onReady(ciphertext)
            }
        }
    }

    fun decrypt(text: String?) = launchBusy {
        result = if (text.isNullOrBlank()) DecryptOutcome.NotAMessage else encrogram.decrypt(text)
    }

    fun clearResult() {
        result = null
    }

    fun generate() = launchBusy {
        val words = encrogram.generatePhrase()
        generatedBits = encrogram.entropyBits(words.size)
        generated = words
    }

    fun useGenerated() {
        val words = generated ?: return
        generated = null
        encrogram.rotationReminder.markNewPhrase()
        unlock(words.joinToString(" "))
    }

    fun cancelGenerated() {
        generated = null
    }

    /** false, wenn der Name zu lang ist. */
    fun saveName(name: String): Boolean {
        val trimmed = name.trim()
        if (!InnerPayload.nameFits(trimmed)) return false
        encrogram.settings.senderName = trimmed
        senderName = trimmed
        return true
    }

    fun lock() = encrogram.lock()

    /** Encrogram ist nicht mehr sichtbar: erzeugte und halb getippte Sätze verwerfen. */
    fun onHidden() {
        generated = null
        resetCount++
    }

    private fun clearSensitive() {
        message = ""
        result = null
        generated = null
        addingPhrase = false
    }

    private fun launchBusy(block: suspend () -> Unit) {
        if (busy) return
        busy = true
        error = null
        viewModelScope.launch {
            try {
                block()
            } finally {
                busy = false
            }
        }
    }
}
